name: Docker Build and Push

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: suraj0294/log-analyser:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $IMAGE_TAG .

      - name: Log in to Docker Hub
        env: 
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echop "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - name: PUSH DOCKER image
        run: docker push $IMAGE_TAG